### ISSUE TITLE
Ne prikazuje naziv grupe

### ISSUE THREAD

**Issue by mradmanovac** [ijanosevic/assignments#10]
U pregledu domaćih se ne vidi naziv grupe.

**Comment by sloba37android** [comment]
ovo ne radi za rolu 2, jer u upitu se spajaju tabela user i assignments, a ime grupe se nalazi u tabeli group.

**Comment by mradmanovac** [comment]
Skinuo sam fajlove i nad njima radim izmenu.Ovo je novi upit.Javljam kada postavim fajlove na server.SELECT assignments.id, assignments.title, assignments.description, groups.name, assignments.download_url, assignments.created_at FROM assignments INNER JOIN users ON assignments.group_id=users.group_idINNER JOIN groupsON assignments.group_id = groups.id 

    On Sunday, 30 April 2017, 9:01, sloba37android <notifications@github.com> wrote:
 

 ovo ne radi za rolu 2, jer u upitu se spajaju tabela user i assignments, a ime grupe se nalazi u tabeli group.—

**Comment by mradmanovac** [comment]
Rešeno.
